#Limited configuration instead of default_config
#https://www.home-assistant.io/integrations/default_config/
automation:
frontend:
history:
logbook:

homeassistant:
  name: Home
  unit_system: metric 
  time_zone: America/Chicago
  latitude: 41.881832
  longitude: -87.623177
  elevation: 181
  currency: USD
  country: US
  temperature_unit: C

logger:
  default: warn
  logs:
    custom_components.sensi: debug
