name: Pre-release
on:
  workflow_dispatch:
    inputs:
      pre_release_version:
        description: 'Pre-release version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Create GitHub Release
        uses: aaiezza/create-release@master
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_branch: ${{ github.ref_name }}
          tag: ${{ github.event.inputs.pre_release_version }}
          draft: false
          prerelease: true

